### ISSUE TITLE
The "Publish" button only appears after saving and re-opening the edit modal

### ISSUE THREAD

**Issue by deanebarker** [episerver/episerver-labs-content-manager-docs#5]
If you create new content, there is not "Publish" button in the bottom left of the edit modal. If you save it, the edit modal closes. If you re-open the edit modal, there is a "Publish" button.

If someone has publishing permissions, there should be a "Publish" button on the modal at all times.

**Comment by tomahg** [comment]
With yesterday's update (v.0.3.0) the publish-button is shown, but it is disabled.

![image](https://user-images.githubusercontent.com/1119118/96778041-5fc63680-13eb-11eb-8a97-f67a18711198.png)

**Comment by barteksekula** [comment]
Due to technical issues we cannot support this.

The item needs to be created first and only then we can calculate if this item can be published, marked as ready to publish etc.

The reason is that we support all kinds of content providers and it's not possible to determine what we might do with the item until it is physically created.

**Comment by tomahg** [comment]
If you could do both create and then publish, without closing the modal dialog - I think it will be much better.

Closing the dialog, making the user have to locate the content, and then publish it, makes it much more difficult.

**Comment by barteksekula** [comment]
You're right. I'll look what can be done.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.ContentManager&v=0.5.3
