### ISSUE TITLE
Grid view button does not appear in edit mode

### ISSUE THREAD

**Issue by oyvindwh** [episerver/episerver-labs-content-manager-docs#9]
When installing the package we do not get the button to switch to grid view. See attachment.

![image](https://user-images.githubusercontent.com/106393/90753162-89be8800-e2d8-11ea-9ded-2501a71494ae.png)

**Comment by oyvindwh** [comment]
Looks like <add key="contentchildren:ContentContainers" value="" /> is not in use in the package.

By adding this code, the gridview shows as accepted:

public class SearchContentViewContentData : SearchContentView<GridContainerPage>
    {
    }

**Comment by gregwiechec** [comment]
The Grid View view is not added to all content types by default.

You can do this using `IsViewEnabled ` flag, but it's not recommended, because then the view will be added for example to all Commerce types.

Instead, please register Grid View for Content Types where it should be used:

````
[ServiceConfiguration(typeof(ViewConfiguration))]
public class NewsListGridView : SearchContentView<NewsPage>
{
}
````

We updated the documentation about this:
https://github.com/episerver/episerver-labs-content-manager-docs/blob/master/GridView.md#gridview-ui-search-component
